[package]
name = "hello-halo2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = "0.2.0"
plotters = "0.3.4"

[dev-dependencies]
gcd = "2.3.0"
rand = "0.8.5"
